plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    alias libs.plugins.modDevGradleLegacy
    alias libs.plugins.kotlinDevGradleLegacy
    alias libs.plugins.lombokLegacy
    alias libs.plugins.kotlinLombokLegacy
    alias libs.plugins.spotless
    id 'org.spongepowered.mixin' version '0.7.+'
}

version = providers.gradleProperty('buildVersion').getOrElse(mod_version)
group = maven_group

def isRelease = providers.gradleProperty('releaseBuild').map { it.toBoolean() }.getOrElse(true)

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
    withSourcesJar()
}

kotlin {
    jvmToolchain(17)
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

configurations {
    libraries
    api.extendsFrom libraries

    localImplementation
    runtimeClasspath.extendsFrom localImplementation
    compileOnly.extendsFrom localImplementation

    yogaSources
    taffyLibrary
}

apply from: "$projectDir/gradle/scripts/moddevgradle.gradle"
apply from: "$projectDir/dependencies.gradle"
apply from: "$projectDir/gradle/scripts/resources.gradle"
apply from: "$projectDir/gradle/scripts/jars.gradle"
apply from: "$projectDir/gradle/scripts/repositories.gradle"
apply from: "$projectDir/gradle/scripts/spotless.gradle"

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
    options.compilerArgs << "-Xlint:-deprecation" << "-Xlint:-removal"
}

jar{
    exclude "**/.cache"
    exclude "**/SimplifiedToTraditional.properties"
}

tasks.register("printVersion") {
    doLast {
        println(project.version)
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        if (isRelease) {
            maven {
                name = "PtcrysReleases"
                url = uri("https://maven.ptcrys.net/releases")
                credentials {
                    username = project.findProperty('ptcrysUsername')
                    password = project.findProperty('ptcrysPassword')
                }
            }
        } else {
            maven {
                name = "PtcrysSnapshots"
                url = uri("https://maven.ptcrys.net/snapshots")
                credentials {
                    username = project.findProperty('ptcrysUsername')
                    password = project.findProperty('ptcrysPassword')
                }
            }
        }
    }
}

// IDEA不再自动下载依赖项的源码/javadoc jar，因此需要显式启用此行为。
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
